### ISSUE TITLE
Java агента в K8S

### ISSUE THREAD

**Issue by VasilenkovDenis** [VasilenkovDenis/instructions#1]
# Настройка Java-агента New Relic в Docker и Kubernetes

## Шаг 1: Загрузка и распаковка агента New Relic

1. Скачайте Java-агент:
   ```bash
   curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
   ```
2. Распакуйте агент в папку с приложением:
   ```bash
   unzip newrelic-java.zip -d /opt/newrelic
   ```
   > **Важно**: Агент Java нужно распаковать в директорию внутри контейнера, которая будет доступна во время выполнения приложения.  
   > Если агент будет расположен в другом месте, убедитесь, что `.jar` файл агента **не** находится в директориях, указанных в `java.endorsed.dirs` или в пути к классам.

---

## Шаг 2: Настройка агента New Relic

1. Откройте файл `newrelic.yml` и внесите изменения:

   ```yaml
   common: &default_settings
     license_key: '0123456789-123456789-123456789-123456789'  # Ключ-заглушка, замените на свой
     app_name: "MY_AWESOME_APP"                               # Название приложения, замените на своё
     host: "gmonit-collector.<DOMAIN>.ru"                     # Домен коллектора, получите у GMonit
     agent_enabled: true
     log_level: info
     log_file_path: stdout
   ```

---

## Шаг 3: Подготовка Docker-образа с агентом

1. В директории, где хранится ваш `Dockerfile` для Java-приложения, добавьте копирование файлов агента в образ (пример для OpenJDK 11):
   ```dockerfile
   FROM openjdk:11-jre-slim

   # Копируем агента New Relic в контейнер
   COPY opt/newrelic/ /opt/newrelic/

   # Копируем ваше Java-приложение в контейнер
   COPY out/ /app

   WORKDIR /app

   # Запускаем приложение с подключённым Java-агентом
   ENTRYPOINT ["java", "-javaagent:/opt/newrelic/newrelic.jar", "com.example.HelloWorldServer"]
   ```

2. Выполните команду для пересборки образа:
   ```bash
   docker build -t my-java-app-with-newrelic:latest .
   ```

3. Загрузите Docker-образ в кластер Kubernetes (пример для kind):
   ```bash
   kind load docker-image my-java-app-with-newrelic:latest
   ```

---

## Шаг 4: Модификация Deployment для Kubernetes

1. Измените `Deployment`-манифест для вашего Java-приложения, чтобы использовать новый образ с агентом.  
   Откройте ваш `.yaml` манифест и измените секцию контейнера, указав новый образ с Java-агентом, например:
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: my-java-app
   spec:
     replicas: 3
     ...
     template:
       spec:
         containers:
           - name: my-java-app-container
             image: my-java-app-with-newrelic:latest
             ...
   ```
   > Эта строка указывает Kubernetes использовать Docker-образ, в который включён Java-агент.

2. Выполните команду для обновления приложения в Kubernetes:
   ```bash
   kubectl apply -f my-java-app-deployment.yaml
   ```
   (где `my-java-app-deployment.yaml` — ваш файл манифеста)

---

## Шаг 5: Проверка работы агента

1. Убедитесь, что ваши Pod'ы запущены:
   ```bash
   kubectl get pods -l app=my-java-app
   ```

2. Проверьте логи New Relic агента, чтобы убедиться, что он работает корректно:
   ```bash
   kubectl exec -it <имя_пода> -- cat /opt/newrelic/logs/newrelic_agent.log
   ```

3. Проверьте доступность портов:
   ```bash
   curl -v telnet://collector.tseries.ru:443
   ```
   Если соединение успешно, то Java-агент сможет передавать метрики и данные в коллектор GMonit.
   ```bash
   curl -v telnet://<ваш_домен_или_IP>:80
   ```
   Аналогичная проверка для другого порта.
   ```bash
   curl http://localhost:30000
   ```
   Проверка доступа к приложению извне кластера.

### Подробнее

Подробнее о конфигурации Java-агента можно узнать в официальной документации:
[Java Agent Configuration (New Relic)](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/)
