### ISSUE TITLE
Java агента в K8S используя init-контейнер

### ISSUE THREAD

**Issue by VasilenkovDenis** [VasilenkovDenis/instructions#2]
# Настройка Java-агента New Relic через init-контейнер в Kubernetes

## Шаг 1: Загрузка и распаковка агента New Relic

1. Скачайте Java-агент:
   ```bash
   curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
   ```
2. Распакуйте агент в папку с приложением:
   ```bash
   unzip newrelic-java.zip -d /opt/newrelic
   ```
   > **Важно**: Агент Java нужно распаковать в директорию внутри контейнера, которая будет доступна во время выполнения приложения.  
   > Если агент будет расположен в другом месте, убедитесь, что `.jar` файл агента **не** находится в директориях, указанных в `java.endorsed.dirs` или в пути к классам.

---

## Шаг 2: Настройка агента New Relic

1. Откройте файл `newrelic.yml` и внесите изменения:
   ```yaml
   common: &default_settings
     license_key: '0123456789-123456789-123456789-123456789'  # Ключ-заглушка, замените на свой
     app_name: "MY_AWESOME_APP"                               # Название приложения, замените на своё
     host: "gmonit-collector.<DOMAIN>.ru"                     # Домен коллектора, получите у GMonit
     agent_enabled: true
     log_level: info
     log_file_path: stdout
   ```
2. Создайте ConfigMap из этого файла:
   ```bash
   kubectl create configmap newrelic-config --from-file=newrelic.yml
   ```

---

### 3.1. Добавьте `emptyDir` volume и ConfigMap в секцию `volumes`
Пример (фрагмент манифеста Deployment):
```yaml
volumes:
  - name: newrelic-agent
    emptyDir: {}
  - name: newrelic-config
    configMap:
      name: newrelic-config
      items:
        - key: newrelic.yml
          path: newrelic.yml
```

### 3.2. Добавьте init-контейнер для загрузки и распаковки Java-агента
```yaml
initContainers:
  - name: init-newrelic-agent
    image: curlimages/curl:latest
    command: ['sh', '-c']
    args:
      - >
        curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip &&
        unzip newrelic-java.zip -d /newrelic &&
        rm newrelic-java.zip
    volumeMounts:
      - name: newrelic-agent
        mountPath: /newrelic
```

### 3.3. Настройте основной контейнер приложения
```yaml
containers:
  - name: my-java-app
    image: my-java-app:latest  # Ваш существующий образ
    volumeMounts:
      - name: newrelic-agent
        mountPath: /newrelic
      - name: newrelic-config
        mountPath: /newrelic/newrelic.yml
        subPath: newrelic.yml
    env:
      - name: JAVA_TOOL_OPTIONS
        value: "-javaagent:/newrelic/newrelic.jar"
```
> **Важно**: Путь к агенту в `JAVA_TOOL_OPTIONS` (`-javaagent:/newrelic/newrelic.jar`) должен совпадать с тем, куда мы распаковали New Relic в init-контейнере.

---

## Шаг 4: Применение изменений

1. Сохраните обновлённый Deployment-манифест в файл, например `my-java-app-deployment.yaml`.
2. Примените манифест командой:
   ```bash
   kubectl apply -f my-java-app-deployment.yaml
   ```

---

## Шаг 5: Проверка работы Java-агента

1. Проверьте состояние Pod'ов:
   ```bash
   kubectl get pods -l app=my-java-app
   ```
2. Убедитесь, что init-контейнер успешно выполнился:
   ```bash
   kubectl describe pod <имя_пода>
   ```
   В разделе **Init Containers** должен быть статус `Completed`.

3. Посмотрите логи приложения и убедитесь, что Java-агент запускается:
   ```bash
   kubectl logs <имя_пода> --container=my-java-app
   ```
   В логах должны быть сообщения от Java-агента.

4. Проверьте соединение с коллектором GMonit (пример):
   ```bash
   kubectl exec -it <имя_пода> -- curl -v telnet://gmonit-collector.<DOMAIN>.ru:443
   ```
   Если соединение успешно, значит агент сможет передавать данные в коллектор.
